#
# rustfmt.toml
#

max_width  = 100
tab_spaces = 4
hard_tabs  = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_params_layout = "Tall"
type_punctuation_density = "Wide"

force_explicit_abi = true
use_try_shorthand = true
fn_single_line = true
format_strings = true
normalize_comments = true
format_code_in_doc_comments = true
